-- =========================================
-- Database Schema — Premier League & World Cup Predictor
-- =========================================

-- Tabel predictions: menyimpan tebakan skor pertandingan dari user
create table public.predictions (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  match_id integer not null,
  home_team character varying(255) not null,
  away_team character varying(255) not null,
  predicted_home_score integer not null,
  predicted_away_score integer not null,
  actual_home_score integer null,
  actual_away_score integer null,
  status character varying(50) null default 'pending'::character varying,
  created_at timestamp with time zone null default now(),
  constraint predictions_pkey primary key (id),
  constraint predictions_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

-- Tabel profiles: data profil user, relasi 1:1 ke auth.users
create table public.profiles (
  user_id uuid not null,
  favorite_team_id integer null,
  favorite_team_name character varying(255) null,
  updated_at timestamp with time zone null default now(),
  username character varying(50) null,
  full_name character varying(255) null,
  avatar_url text null,
  bio text null,
  constraint profiles_pkey primary key (user_id),
  constraint profiles_username_key unique (username),
  constraint profiles_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

-- Tabel watchlist: pertandingan yang di-bookmark user
create table public.watchlist (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  match_id integer not null,
  home_team character varying(255) not null,
  away_team character varying(255) not null,
  match_date timestamp with time zone null,
  notes text null,
  created_at timestamp with time zone null default now(),
  constraint watchlist_pkey primary key (id),
  constraint watchlist_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

-- Tabel wc_historical_matches: histori pertandingan World Cup 2014-2026
-- Sumber data: openfootball/worldcup.json, di-ETL manual via scripts/etl_wc_history.py
create table if not exists wc_historical_matches (
    id bigint generated always as identity primary key,
    season int not null,
    match_num int,
    round text,
    match_date date,
    team1 text not null,
    team2 text not null,
    team1_goals int,
    team2_goals int,
    "group" text,
    ground text,
    is_placeholder boolean default false,
    created_at timestamptz default now()
);

create unique index if not exists idx_wc_unique_match
    on wc_historical_matches (season, match_num);
create index if not exists idx_wc_teams on wc_historical_matches (team1, team2);
create index if not exists idx_wc_season on wc_historical_matches (season);

-- Tabel pl_historical_matches: histori pertandingan Premier League 5 musim terakhir
-- Sumber data: openfootball/football.json, di-ETL manual via scripts/etl_pl_history.py
create table if not exists pl_historical_matches (
    id bigint generated always as identity primary key,
    season text not null,
    match_num int,
    round text,
    match_date date,
    team1 text not null,
    team2 text not null,
    team1_goals int,
    team2_goals int,
    created_at timestamptz default now()
);

create unique index if not exists idx_pl_unique_match
    on pl_historical_matches (season, match_num);
create index if not exists idx_pl_teams on pl_historical_matches (team1, team2);
create index if not exists idx_pl_season on pl_historical_matches (season);